//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.08 at 06:44:59 PM MSK 
//


package com.skat.smev.fns.model.statuses;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ИдЗапрос" use="required" type="{urn://x-artefacts-fns-statdokreg/types/4.0.2}ИдЗапросТип" />
 *       &lt;attribute name="ИдЗапросФНС" use="required" type="{urn://x-artefacts-fns-statdokreg/types/4.0.2}ИдЗапросТип" />
 *       &lt;attribute name="СтатусДок" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn://x-artefacts-fns-statdokreg/types/4.0.2}string_2">
 *             &lt;enumeration value="10"/>
 *             &lt;enumeration value="20"/>
 *             &lt;enumeration value="21"/>
 *             &lt;enumeration value="30"/>
 *             &lt;enumeration value="40"/>
 *             &lt;enumeration value="48"/>
 *             &lt;enumeration value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "STATDOKREGResponse")
public class STATDOKREGResponse {

    @XmlAttribute(name = "\u0418\u0434\u0417\u0430\u043f\u0440\u043e\u0441", required = true)
    protected String идЗапрос;
    @XmlAttribute(name = "\u0418\u0434\u0417\u0430\u043f\u0440\u043e\u0441\u0424\u041d\u0421", required = true)
    protected String идЗапросФНС;
    @XmlAttribute(name = "\u0421\u0442\u0430\u0442\u0443\u0441\u0414\u043e\u043a", required = true)
    protected String статусДок;

    /**
     * Gets the value of the идЗапрос property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдЗапрос() {
        return идЗапрос;
    }

    /**
     * Sets the value of the идЗапрос property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдЗапрос(String value) {
        this.идЗапрос = value;
    }

    /**
     * Gets the value of the идЗапросФНС property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдЗапросФНС() {
        return идЗапросФНС;
    }

    /**
     * Sets the value of the идЗапросФНС property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдЗапросФНС(String value) {
        this.идЗапросФНС = value;
    }

    /**
     * Gets the value of the статусДок property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getСтатусДок() {
        return статусДок;
    }

    /**
     * Sets the value of the статусДок property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setСтатусДок(String value) {
        this.статусДок = value;
    }

}
