//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.08 at 06:48:07 PM MSK 
//


package com.skat.smev.fns.model.docs;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.skat.smev.election package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.skat.smev.election
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PRDDOKREGResponse }
     * 
     */
    public PRDDOKREGResponse createPRDDOKREGResponse() {
        return new PRDDOKREGResponse();
    }

    /**
     * Create an instance of {@link PRDDOKREGRequest }
     * 
     */
    public PRDDOKREGRequest createPRDDOKREGRequest() {
        return new PRDDOKREGRequest();
    }

}
