//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.08 at 06:48:07 PM MSK 
//


package com.skat.smev.fns.model.docs;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ИдЗапрос" use="required" type="{urn://x-artefacts-fns-prddokreg/types/4.0.0}ИдЗапросТип" />
 *       &lt;attribute name="ВидГосРег" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn://x-artefacts-fns-prddokreg/types/4.0.0}string_1">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PRDDOKREGRequest", namespace = "urn://x-artefacts-fns-prddokreg/root/311-39/4.0.0")
public class PRDDOKREGRequest {

    @XmlAttribute(name = "\u0418\u0434\u0417\u0430\u043f\u0440\u043e\u0441", required = true)
    protected String идЗапрос;
    @XmlAttribute(name = "\u0412\u0438\u0434\u0413\u043e\u0441\u0420\u0435\u0433", required = true)
    protected String видГосРег;

    /**
     * Gets the value of the идЗапрос property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдЗапрос() {
        return идЗапрос;
    }

    /**
     * Sets the value of the идЗапрос property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдЗапрос(String value) {
        this.идЗапрос = value;
    }

    /**
     * Gets the value of the видГосРег property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getВидГосРег() {
        return видГосРег;
    }

    /**
     * Sets the value of the видГосРег property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setВидГосРег(String value) {
        this.видГосРег = value;
    }

}
